version: '3.8'
services:
    cache:
        build: ./cache
        container_name: pbl-cache
        tty: true
        ports: 
            - 6666:6666

    gateway:
        build: ./gateway
        container_name: pbl-gateway
        depends_on: [cache]
        tty: true
        ports: 
            - 7171:7171

    postgres:
        build:
            context: ./postgres
            args:
                - POSTGRES_VERSION=13
        container_name: pbl-postgres
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=orders_db
            - POSTGRES_USER=default_user
            - POSTGRES_PASSWORD=secret

    orders-service1:
        build: 
            context: ./orders-service
            # args:
            #     - SERVICE_PORT=8080
        container_name: pbl-orders-service1
        volumes:
            - ./orders-service:/orders-service
            - ~/.m2:/root/.m2
        tty: true
        depends_on: [postgres, gateway]
        environment: 
            - SERVICE_PORT=8080
            - SERVICE_NAME=orders-service
            - SERVICE_ADDRESS=orders-service1
            - GATEWAY_ADDRESS=gateway
            - GATEWAY_PORT=7171
        ports:
            - 8080:8080

    orders-service2:
        build: 
            context: ./orders-service
            # args:
            #     - SERVICE_PORT=8081
        container_name: pbl-orders-service2
        volumes:
            - ./orders-service:/orders-service
            - ~/.m2:/root/.m2
        tty: true
        depends_on: [postgres, gateway]
        environment: 
            - SERVER_PORT=8081
            - SERVICE_NAME=orders-service
            - SERVICE_ADDRESS=orders-service2
            - GATEWAY_ADDRESS=gateway
            - GATEWAY_PORT=7171
        ports:
            - 8081:8081

    mongo:
        build: 
            context: ./mongo
            args:
                - MONGO_VERSION=4
        container_name: pbl-mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongo/data:/data/db
            - ./mongo/mongo_config:/data/configdb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret

    reports-service1:
        build:
            context: ./reports-service
            args:
                - NODE_VERSION=15.1.0
        container_name: pbl_reports_service1
        ports:
            - 9090:9090
        tty: true
        volumes:
            - ./reports-service:/reports-service
        environment:
            - SERVER_PORT=9090
            - SERVICE_NAME=reports-service
            - SERVICE_ADDRESS=reports-service1
            - GATEWAY_ADDRESS=gateway
            - GATEWAY_PORT=7171
        depends_on: [mongo, gateway]