version: '3.8'
services:
    cache:
        build: ./cache
        container_name: pbl-cache
        tty: true
        ports: 
            - 6666:6666

    gateway:
        build: ./gateway
        container_name: pbl-gateway
        depends_on: [cache]
        tty: true
        ports: 
            - 7171:7171

    postgres:
        build:
            context: ./postgres
            args:
                - POSTGRES_VERSION=13
        container_name: pbl-postgres
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=orders_db
            - POSTGRES_USER=default_user
            - POSTGRES_PASSWORD=secret

    orders-service1:
        build: 
            context: ./orders-service
            # args:
            #     - SERVICE_PORT=8080
        container_name: pbl-orders-service1
        volumes:
            - ./orders-service:/orders-service
            - ~/.m2:/root/.m2
        tty: true
        depends_on: [postgres, gateway]
        environment: 
            - SERVICE_PORT=8080
            - SERVICE_NAME=orders-service
            - SERVICE_ADDRESS=orders-service1
            - GATEWAY_ADDRESS=gateway
            - GATEWAY_PORT=7171
        ports:
            - 8080:8080

    # orders-service2:
    #     build: 
    #         context: ./orders-service
    #         # args:
    #         #     - SERVICE_PORT=8081
    #     container_name: pbl-orders-service2
    #     volumes:
    #         - ./orders-service:/orders-service
    #         - ~/.m2:/root/.m2
    #     tty: true
    #     depends_on: [postgres, gateway]
    #     environment: 
    #         - SERVER_PORT=8081
    #         - SERVICE_NAME=orders-service
    #         - SERVICE_ADDRESS=orders-service2
    #         - GATEWAY_ADDRESS=gateway
    #         - GATEWAY_PORT=7171
    #     ports:
    #         - 8081:8081