# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rake", "~> 13.0"

gem "activerecord", "~> 6.0"

gem "pg", "~> 1.2"

gem "pry", "~> 0.13.1"

gem "sinatra", "~> 2.1"

gem "sinatra-contrib", "~> 2.1"

gem "json", "~> 2.3"

gem "sucker_punch", "~> 2.1"

gem "rest-client", "~> 2.1"
